name: Build Project

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Project

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .Net Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          cache: true
          cache-dependency-path: '**/*.csproj'

      - name: Build .Net
        run: |
          dotnet restore 
          dotnet build --configuration Release

      - name: Run tests
        run: |
          dotnet test --configuration Release --no-build --verbosity normal --results-directory ./test-results --logger "trx;LogFileName=test_results.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results